version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    container_name: luxstay-api
    build: .
    image: luxstay-api
    volumes:
      - .:/usr/src/luxstay-api
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db
